'use client'

// Auto-generated by ShaniAI
// Lightweight EIP-1193 + viem wallet helper for Sepolia
import { createWalletClient, custom } from 'viem'
import { sepolia } from 'viem/chains'

const SEPOLIA_CHAIN_ID_HEX = '0xaa36a7'; // 11155111

function getInjected(): any | null {
  if (typeof window === 'undefined') return null;
  return (window as any).ethereum || null;
}

async function ensureSepolia(eth: any) {
  try {
    const currentHex = await eth.request({ method: 'eth_chainId' });
    if ((currentHex || '').toLowerCase() === SEPOLIA_CHAIN_ID_HEX) return;
    try {
      await eth.request({ method: 'wallet_switchEthereumChain', params: [{ chainId: SEPOLIA_CHAIN_ID_HEX }] });
      return;
    } catch (err: any) {
      if (err?.code === 4902 || (err?.message || '').toLowerCase().includes('unrecognized')) {
        await eth.request({
          method: 'wallet_addEthereumChain',
          params: [{
            chainId: SEPOLIA_CHAIN_ID_HEX,
            chainName: 'Sepolia',
            nativeCurrency: { name: 'Sepolia ETH', symbol: 'ETH', decimals: 18 },
            rpcUrls: ['https://rpc.sepolia.org'],
            blockExplorerUrls: ['https://sepolia.etherscan.io']
          }]
        });
        return;
      }
      throw err;
    }
  } catch (e) {
    console.warn('ensureSepolia failed:', e);
  }
}

export async function getWalletClient() {
  const eth = getInjected();
  if (!eth) throw new Error('No injected wallet found');
  await ensureSepolia(eth);
  const accounts = await eth.request({ method: 'eth_requestAccounts' });
  if (!accounts || accounts.length === 0) throw new Error('No account');
  return createWalletClient({ chain: sepolia, account: accounts[0] as any, transport: custom(eth) });
}
